### ISSUE TITLE
PermissionDeniedError in Chrome

### ISSUE THREAD

**Issue by hank** [trailofbits/tubertc#71]
I have Chrome 47, and this refuses to work.  I constantly get a MEDIA_ERR PermissionDeniedError indicating my camera and mic cannot be found.  It almost works in Firefox with the Mic being detected but no video.  Please help.

**Comment by hank** [comment]
This also happens on my phone in Chrome.

**Comment by dguido** [comment]
Trying loading the page over HTTPS. Chrome 47+ blocks non-TLS WebRTC.

**Comment by hank** [comment]
Awesome that worked - please update the documentation/error window to indicate this.  Cheers!
