### ISSUE TITLE
Multiple Connection to a single user

### ISSUE THREAD

**Issue by praty22** [trailofbits/tubertc#78]
Just installed tubertc on local machine . Facing a weird issue that on joining of 4th user , it gets connected twice to one of the user in conference .
Which result in two video box of himself in the user UI to whom it get connected twice .
I thought it might be an issue with my local installation so i tried this scenario on your live demo given on github
[https://afternoon-citadel-6116.herokuapp.com/](https://afternoon-citadel-6116.herokuapp.com/)
the same issue is existing there also .
Firefox version : 61.0.1
Server : ubuntu 14.04
No errors in server logs.
I am quite surprised that no one till date faces this issue .
It would be great if someone could help me around this .

**Comment by yying** [comment]
@praty22 I'm looking into the issue

**Comment by yying** [comment]
@praty22 closed with 7b22079a9ccbdbe10ce62c52f5404a9318fea032

**Comment by praty22** [comment]
Is the issue resolved?

**Comment by yying** [comment]
@praty22 Yes, the multiple video boxes issue should be resolved.

**Comment by praty22** [comment]
Yes this issue is sorted.
Thanks !
