### ISSUE TITLE
When trying to open on Heroku, I get an error.

### ISSUE THREAD

**Issue by catsdgs** [trailofbits/tubertc#98]
The error looks like this: at=error code=H10 desc="App crashed" method=GET path="/" host=[ME] request_id=[ME] fwd="[ME]" dyno= connect= service= status=503 bytes= protocol=https. I cannot figure out why this keeps happening.

**Comment by beeman** [comment]
@catsdgs I updated the packages and that seemed to have fixed it https://github.com/beeman/tubertc
